### ISSUE TITLE
Compare the Java and R version

### ISSUE THREAD

**Issue by littlehappi** [ServiceNow/stl-decomp-4j#13]
Hi @jcrotinger,
I start one new issue to discuss the problem of java version. The parameters of the stl is set with inner_loop=1, outer_loop=3, setPeriodic, and etc. Sometimes there is a sudden raise in the java-stl trend and the season data is also different from the r-stl.

**Comment by littlehappi** [comment]
@jcrotinger , 
Here is the java code:
SeasonalTrendLoess smoother = builder.
                    setPeriodLength(1440).
                    setPeriodic().
                    setTrendWidth(100).
                    setRobust().
                    buildSmoother(values);
I have found the reason for the sudden rise of java version. The outer_loop=3 is not enough to converge the noise weights for java stl, and outer_loop=15 is better. Maybe the R-stl converges faster? I'm trying to figure out the differences between the source code of the two versions. Your advice will be appreciated.

**Comment by jcrotinger** [comment]
@littlehappi  I believe the R interface uses the same settings when "robust" is specified instead of explicitly specifying the inner and outer iteration count - an outer count of 15 and an inner count of 1. What does your R command look like? The convergence should be the same or very nearly so since we agree with Fortran basically to roundoff.

**Comment by littlehappi** [comment]
@jcrotinger I found that the season window width is different if chosing 'periodic'.
In R:
            periodic <- TRUE
            s.window <- 10 * n + 1
            s.degree <- 0
In java:
		if (fPeriodic) {
			fSeasonalWidth = 100 * data.length;
			fSeasonalDegree = 0;
		}

**Comment by jcrotinger** [comment]
That shouldn't be an issue - that should just make it even closer to exactly periodic. This is saying "use flat interpolation" (averaging) and use a window that is many times bigger than the length of the data set. Since this is done on the cyclic sub-series, either one is likely to generate a very flat fit to the cyclic subseries.

**Comment by littlehappi** [comment]
@jcrotinger 
The java code to call the R interface is:
        re.eval(" p<-unlist(passenger)");
        re.eval(" pt<-ts(p,frequency=1440,start=" + 0 + ") ");
        re.eval("stlResult<-stl(pt, s.window = 'periodic', t.window =" + 100
                + " , robust = TRUE, inner=1,outer=3)");
And here is the java result with outer_loop=15:
![2018-01-23 11 18 29](https://user-images.githubusercontent.com/20963433/35256523-42b4c070-002f-11e8-95f7-856198e2612e.png)

**Comment by jcrotinger** [comment]
@littlehappi Any chance you could clone the repo and add your example (data and R example included)? I'd be happy to take a further look.

**Comment by littlehappi** [comment]
@jcrotinger Sorry that the original data is private. You can try the other open dataset with much noise. I am working on that :)

**Comment by jcrotinger** [comment]
@littlehappi Any update based on a public dataset? As I mentioned, the repo includes an example with the CO<sub>2</sub> data set already and gets the same results within round-off size errors as the Fortran that underlies the R package.

**Comment by littlehappi** [comment]
@jcrotinger Sorry that i'm busy with other things. But the java-stl does work well with the CO2 data and many other datasets.
