### ISSUE TITLE
How is this different from stl-java?

### ISSUE THREAD

**Issue by timeseriesforecast** [ServiceNow/stl-decomp-4j#4]
May i know how this differ from https://github.com/brandtg/stl-java. looking into algo both looks similar.. but time taken and results are differing? can u explain it?

**Comment by jcrotinger** [comment]
@timeseriesforecast, [STL-Java](https://github.com/brandtg/stl-java) is an implementation of the same algorithm on top of a general purpose LOESS smoother, and was the first thing I tried when looking for a Java implementation. While this *should* work, it would not be as fast as stl-decomp-4j, which uses a LOESS smoother designed specifically for the STL algorithm (a direct port of the Fortran one, which assumes equally spaced points and handles the robustness iterations in the STL part of the algorithm instead of in the LOESS algorithm). Furthermore, the current stl-java implementation has some issues, for instance [this one](https://github.com/brandtg/stl-java/issues/9) that I opened last year. Given these issues, I think stl-java will likely be deprecated once folks have have tried stl-decomp-4j.
