### ISSUE TITLE
Not an Issue; Doubt in setting seasonal width/periodic

### ISSUE THREAD

**Issue by timeseriesforecast** [ServiceNow/stl-decomp-4j#5]
How to Find whether the series is periodic or not? for decompose we need to set seasonal width/periodic. i need to decompose a different dataset. i know only the period length. how to choose which one to set? how setSeasonalWidth() and setPeriodic() differs?

**Comment by jcrotinger** [comment]
@timeseriesforecast,

The length of the period is set by `Builder.setPeriodLength(int period)`.

 The width of the smoother used to smooth the seasonal sub-series is set by `Builder.setSeasonalWidth(int width)`. 

If you want to do a fit in which the seasonal component is exactly periodic, rather than having a time-varying periodic component, then you can call `Builder.setPeriodic()` instead of setting the seasonal smoother width. (This is just a short-cut that sets the seasonal sub-series smoother width to be 100 * the length of the data set and the degree of the seasonal smoother to be 0 (a weighted average instead of a polynomial). I added it to mimic the ability to set the seasonal width to the string "periodic" in the R interface.)

Whether the data is periodic or not is a separate issue. If you're going to use the STL usually you have some reason to believe that there is a seasonal component that you'd like to extract from the signal.
