### ISSUE TITLE
the seasonal cycle

### ISSUE THREAD

**Issue by lmxhappy** [ServiceNow/stl-decomp-4j#9]
is it known how long is time length of the seasonal interval?

**Comment by jcrotinger** [comment]
The number of points in a season is specified as an input - the STL algorithm doesn't attempt to figure this out. Usually it is obvious from the context or from observing the data. Also, "time length" doesn't actually matter directly since the STL assumes equally spaced points with no missing data. (Support for missing data could be added - I think by setting the weights to 0 for the missing data points. Hafen's stlplus R package supports missing data, though I haven't confirmed that this is the mechanism.)

**Comment by jcrotinger** [comment]
Let me know if you have any more questions.

**Comment by lmxhappy** [comment]
Thanks very much.
